services:
    gallery.feed.controller:
        class: phpbb_ext_gallery_feed_controller_main
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%

